routes/web.php
<?php

use App\Http\Controllers\DocenteController;
use Illuminate\Support\Facades\Route;
//agregamos los controladores
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\TipoController;
use App\Http\Controllers\EstudianteController;
use App\Http\Controllers\ExternoController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/foo', function () {
    Artisan::call('storage:link');
});

Route::get('/', function () {
    return view('welcome');
});


Route::get('/seguimiento', function () {
    return view('seguimiento');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/seguimientoga',[DocumentController::class,'seguimiento'])->name('doc.seguimiento');

Auth::routes();


Route::resource('forestudiante',EstudianteController::class);
Route::resource('fordocente',DocenteController::class);
Route::resource('forexterno',ExternoController::class);

Route::group(['middleware'=>['auth']],function(){
    Route::resource('roles',RolController::class);
    Route::resource('usuarios',UsuarioController::class);
    Route::put('/changepass',[UsuarioController::class,'updatepass'])->name('pass.update');
    Route::resource('documents',DocumentController::class);
    Route::get('documento/rechazados',[DocumentController::class,'rechazados'])->name('doc.rechazados');
    Route::get('documento/finalizados',[DocumentController::class,'finalizados'])->name('doc.finalizados');

    Route::put('/enviardoc/{doc}',[DocumentController::class,'enviar'])->name('doc.update');
    Route::put('/rechazardoc/{doc}',[DocumentController::class,'rechazar'])->name('doc.updaterecha');
    Route::put('/finalizadodoc/{doc}',[DocumentController::class,'finalizado'])->name('doc.updatefnlzdo');

    Route::resource('tipos', TipoController::class);
});

app/Models/Adjunto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Adjunto extends Model
{
    use HasFactory;
    protected $fillable = [];
    //uno a muchos inversa
    public function documento(){
        return $this->belongsTo(Document::class);
    }
    public function getGetContenidoAttribute(){
        return url("storage/$this->contenido");
    }

    


}

app/Models/Document.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Models\Role;

class Document extends Model
{
    use HasFactory;
    protected $fillable = ['rol_id','tipo_id','codigo_tramite', 'titulo','contenido'];

    //relacion uno a muchos pero inversa
    public function tipo(){
        return $this->belongsTo(Tipo::class);
    }
    //relacion uno a uno
    public function estudiante()
    {
        return $this->hasOne(Estudiante::class);
    }
    //relacion uno a uno
    public function docente()
    {
        return $this->hasOne(Docente::class);
    }
    //relacion uno a uno
    public function externo()
    {
        return $this->hasOne(Externo::class);
    }
    //relacion muchos a muchos
    // public function roles(){
    //     return $this->belongsToMany(Role::class);
    // }
    //relacion uno a muchos
    // public function documentroles(){
    //     return $this->hasMany(DocumentRole::class);
    // }
    //relacion uno a muchos pero inversa
    public function rol(){
        return $this->belongsTo(Role::class);
    }
    //relacion uno a muchos
    public function seguimientos(){
        return $this->hasMany(Seguimiento::class);
    }
    //uno a muchos
    public function adjuntos(){
        return $this->hasMany(Adjunto::class);
    }


}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Document;
use App\Models\DocumentRole;
use App\Models\Seguimiento;
use App\Models\Tipo;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Shmop;
use Spatie\Permission\Models\Role;

class DocumentController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:ver-documento|crear-documento|editar-documento|borrar-documento',['only'=>['index']]);
        $this->middleware('permission:crear-documento',['only'=>['create','store']]);
        $this->middleware('permission:editar-documento',['only'=>['edit','update']]);
        $this->middleware('permission:borrar-documento',['only'=>['destroy']]);
        $this->middleware('permission:enviar-documento',['only'=>['update']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuario = Auth::user()->id;
        $usuario = User::find($usuario);
        $usuariorol = $usuario->roles->first();

        if($usuariorol->id==1){
            // $docs = Document::paginate(5);
            $docs = Document::all();
            // $usuarioroldocs = $usuariorol->documentos;
            $docs = $docs->filter(function ($doc) {
                return $doc->seguimientos->last()->estado == 'Pendiente';
            });
            // dd($docs);
        }else{
            $usuarioroldocs = $usuariorol->documentos;
            $docs = $usuarioroldocs->filter(function ($doc) {
                return $doc->seguimientos->last()->estado == 'Pendiente';
            });
        }

        $documents = Document::paginate(5);
        //dd($usuariorol->documentos->first()->seguimientos->last()->estado);
        $tipos = Tipo::all();
        $oficinas = Role::all();
        return view('documents.index', compact('documents','tipos','oficinas','usuariorol','docs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $tipos = Tipo::pluck('title','title')->all();
        return view('documents.crear',compact('tipos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'tipo_id'=>'required',
            'titulo' => 'required',
            'contenido' => 'required',

        ]);
        $nametipo= $request->input('tipo_id');
        $tipo = Tipo::where('title',$nametipo)->value('id');
        $request->merge(['tipo_id' => $tipo]);


        // $titulo = $request->input('titulo');
        // $contenido = $request->input('contenido');

        // $document= new Document;
        // $document->titulo = $titulo;
        // $document->contenido = $contenido;
        // $document->tipo_id = $tipo;
        // dd($document);
        // $document->save();
        Document::create($request->all());
        return redirect()->route('documents.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        //
       // dd($document->adjuntos->first()->get_contenido);

        $oficinas = Role::all();
        if($document->estudiante){
            $cliente=$document->estudiante;
        }
        elseif($document->docente){
            $cliente=$document->docente;
        }
        else{
            $cliente=$document->externo;
        }
        return view('documents.ver', compact('document','oficinas','cliente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $document)
    {
        return view('documents.editar', compact('document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Document $document)
    {
        //
        request()->validate([
            'titulo' => 'required',
            'contenido' => 'required',
        ]);
        $document->update($request->all());
        return redirect()->route('documents.index');
    }

    public function enviar(Request $request ,Document $doc)
    {
        //
        // request()->validate([
        //     'titulo' => 'required',
        //     'contenido' => 'required',
        // ]);
        $segaprobar =$doc->seguimientos->last();
        $segaprobar->estado = "Aprobado";
        $segaprobar->save();
        // $documentid->request;
        $seguimiento = new Seguimiento;
        $seguimiento->document_id = $doc->id;
        $seguimiento->oficina = $request->oficina;
        $seguimiento->oficina_derivada = $doc->seguimientos->last()->oficina;

        //dd($doc->seguimientos->last()->oficina);
        $seguimiento->save();

        $doc->role_id = Role::where('name',$request->oficina)->value('id');
        $doc->save();


        // $documentrole->role_id=$request->oficina;
        // dd($documentrole);
        // $documentrole->save();

        // $document->update($request->all());
        return redirect()->route('documents.index');
    }
    public function rechazar(Request $request ,Document $doc)
    {
        //
        // request()->validate([
        //     'titulo' => 'required',
        //     'contenido' => 'required',
        // ]);

        // $documentid->request;
        $seguimiento = $doc->seguimientos->last();

        // $documentrole->document_id=$doc->id;
        // $documentrole->role_id=$request->oficina;
        $seguimiento->estado = "Rechazado";
        if($request->comentario){
            $seguimiento->comentario = $request->comentario;
        }



        //  dd($seguimiento);
        $seguimiento->save();
        // $documentrole->estado = "Rechazado";
        // dd($documentrole);
        // $documentrole->save();

        // $document->update($request->all());
        return redirect()->route('documents.index');
    }
    public function finalizado(Document $doc)
    {

        $seguimiento = $doc->seguimientos->last();
        $seguimiento->comentario = "Su tramite esta listo";
        $seguimiento->estado = "Finalizado";//finalizado
        $seguimiento->save();
        return redirect()->route('documents.index');
    }
     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function seguimiento(Request $request){

        $document = Document::firstWhere('codigo_tramite', $request->codseguimiento);
        //dd($document);

        return view('seguimientover', compact('document'));

    }
    public function rechazados(){

        $usuario = Auth::user()->id;
        $usuario = User::find($usuario);
        $usuariorol = $usuario->roles->first();
        if($usuariorol->id==1){
            $docs = Document::all();
            // $usuarioroldocs = $usuariorol->documentos;
            $docs = $docs->filter(function ($doc) {
                return $doc->seguimientos->last()->estado == 'Rechazado';
            });
        }else{
            $usuarioroldocs = $usuariorol->documentos;
            $docs = $usuarioroldocs->filter(function ($doc) {
                return $doc->seguimientos->last()->estado == 'Rechazado';
            });
        }


        $documents = Document::paginate(5);
        // dd($usuariorol->documentos->first()->seguimientos->last()->estado);
        // $plucked = $usuarioroldocs->pluck('speakers.first_day');
        // $filtered = $usuarioroldocs->where('deleted_at', '!=', null);

        // $docs = $docspaginate(5);
        // dd($docs);
        $tipos = Tipo::all();
        $oficinas = Role::all();
        return view('documents.rechazados', compact('docs','tipos','oficinas','usuariorol'));

    }

    public function finalizados(){
        $usuario = Auth::user()->id;
        $usuario = User::find($usuario);
        $usuariorol = $usuario->roles->first();
        if($usuariorol->id==1){
            $docs = Document::all();
            // $usuarioroldocs = $usuariorol->documentos;
            $docs = $docs->filter(function ($doc) {
                return $doc->seguimientos->last()->estado == 'Finalizado';
            });
        }else{
            $usuarioroldocs = $usuariorol->documentos;
            $docs = $usuarioroldocs->filter(function ($doc) {
                return $doc->seguimientos->last()->estado == 'Finalizado';
            });
        }

        return view('documents.finalizados', compact('docs'));
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Document $document)
    {
        $document->delete();
        return redirect()->route('documents.index');
    }



}

resources/views/documents/finalizados.blade.php
@extends('layouts.app')

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading">Documentos Finalizados</h3>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">


                        @can('crear-documento')
                        <a class="btn btn-warning" href="{{ route('documents.create') }}">Nuevo</a>
                        @endcan

                        <table class="table table-striped mt-2">
                                <thead style="background-color:#6777ef">
                                    <th style="display: none;">ID</th>
                                    <th style="color:#fff;">CodigoTramite</th>
                                    <th style="color:#fff;">Tipo Doc</th>
                                    <th style="color:#fff;">Nombre</th>
                                    <th style="color:#fff;">Tramite de:</th>
                                    <th style="color:#fff;">Derivado por:</th>
                                    <th style="color:#fff;">Oficina Actual:</th>
                                    <th style="color:#fff;">Acciones</th>
                              </thead>
                              <tbody>
                        
                            @foreach ($docs as $doc)
                            <tr>
                                <td style="display: none;">{{ $doc->id }}</td>
                                <td>{{ $doc->codigo_tramite }}</td>
                                <td>
                                    @if(!empty($doc->tipo_id))
                                        {{-- @foreach($usuario->getRoleNames() as $rolName) --}}
                                            <h5><span class="badge badge-dark">{{ $doc->tipo->title }}</span></h5>
                                        {{-- @endforeach --}}
                                    @endif
                                </td>

                                @if (!empty($doc->estudiante))
                                    <td>{{ $doc->estudiante->nombre }}</td>
                                    <td>Estudiante</td>
                                @elseif (!empty($doc->docente))
                                    <td>{{ $doc->docente->nombre }}</td>
                                    <td>Docente</td>
                                @else
                                    <td>{{ $doc->externo->nombre }}</td>
                                    <td>Externo</td>
                                @endif
                                <td>
                                    {{ $doc->seguimientos->last()->oficina_derivada }}
                                </td>
                                <td>
                                    {{ $doc->seguimientos->last()->oficina }},{{ $doc->seguimientos->last()->estado }} 
                                </td>
                                <td>
                                    {{-- {!! Form::open(array('route'=>'doc.update','method'=>'PUT')) !!}
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <div class="form-group">
                                                <label for="oficina">Tipo de oficina</label>
                                                {!! Form::select('oficina[]',$oficinas,[],array('class'=>'form-control')) !!}
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <button type="submit" class="btn btn-primary">Enviar</button>
                                        </div>

                                    </div>
                                    {!! Form::close() !!} --}}
                                    {{-- {!! Form::open(array('route'=>'doc.update','method'=>'PUT')) !!} --}}
                                    



                                    <form action="{{ route('documents.destroy',$doc->id) }}" method="POST">
                                        {{-- <form action="{{ route('documents.update',$document->id) }}" method="POST">
                                            @csrf
                                            @method('PUT')

                                                <button type="submit" class="btn btn-primary">Enviar</button>
                                            </div>
                                        </form>                                         --}}
                                        <!-- Default dropright button -->
                                        {{-- <div class="btn-group dropright">
                                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Enviar
                                            </button>
                                            <div class="dropdown-menu">

                                                @foreach ($oficinas as $oficina)
                                                <form action="{{ route('doc.update',$oficina->id) }}" method="GET">
                                                    @csrf
                                                    @method('PUT')

                                                        <button type="submit" class="dropdown-item">{{ $oficina->name }}</button>

                                                </form>
                                                @endforeach
                                            </div>
                                        </div> --}}
                                        @can('editar-documento')
                                        <a class="btn btn-info" href="{{ route('documents.edit',$doc->id) }}">Editar</a>
                                        @endcan
                                        <a class="btn btn-outline-primary" href="{{ route('documents.show',$doc->id) }}">Ver</a>
                                        @csrf
                                        @method('DELETE')
                                        @can('borrar-documento')
                                        <button type="submit" class="btn btn-danger">Borrar</button>
                                        @endcan
                                    </form>

                                </td>
                                {{-- <td>
                                    @can('editar-documento')
                                    <a class="btn btn-primary" href="{{ route('documents.edit', $documento->id)  }}">Editar</a>
                                    @endcan
                                    @can('borrar-documento')
                                    {!! Form::open(['method'=>'DELETE','route'=>['documents.destroy',$documento->id],'style'=>'display:inline']) !!}
                                        {!! Form::submit('Borrar',['class'=>'btn btn-danger']) !!}
                                    {!! Form::close() !!}
                                    @endcan

                                </td> --}}
                            </tr>
                            @endforeach
                        


                            </tbody>
                        </table>

                        <!-- Ubicamos la paginacion a la derecha -->
                        <div class="pagination justify-content-end">
                            {{-- {!! $docs->links() !!} --}}
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/documents/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading">Documentos</h3>
        </div>
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">


                        @can('crear-documento')
                        <a class="btn btn-warning" href="{{ route('documents.create') }}">Nuevo</a>
                        @endcan

                        <table class="table table-striped mt-2">
                                <thead style="background-color:#6777ef">
                                    <th style="display: none;">ID</th>
                                    <th style="color:#fff;">CodigoTramite</th>
                                    <th style="color:#fff;">Tipo Doc</th>
                                    <th style="color:#fff;">Nombre</th>
                                    <th style="color:#fff;">Tramite de:</th>

                                    <th style="color:#fff;">Derivado por:</th>
                                    <th style="color:#fff;">Oficina Actual:</th>
                                    <th style="color:#fff;">Acciones</th>
                              </thead>
                              <tbody>

                            @foreach ($docs as $doc)
                            <tr>
                                <td style="display: none;">{{ $doc->id }}</td>
                                <td>{{ $doc->codigo_tramite }}</td>
                                <td>
                                    @if(!empty($doc->tipo_id))
                                        {{-- @foreach($usuario->getRoleNames() as $rolName) --}}
                                            <h5><span class="badge badge-dark">{{ $doc->tipo->title }}</span></h5>
                                        {{-- @endforeach --}}
                                    @endif
                                </td>
                                @if (!empty($doc->estudiante))
                                    <td>{{ $doc->estudiante->nombre }}</td>
                                    <td>Estudiante</td>
                                @elseif (!empty($doc->docente))
                                    <td>{{ $doc->docente->nombre }}</td>
                                    <td>Docente</td>
                                @else
                                    <td>{{ $doc->externo->nombre }}</td>
                                    <td>Externo</td>
                                @endif

                                <td>
                                    {{ $doc->seguimientos->last()->oficina_derivada }}
                                </td>
                                <td>
                                    {{ $doc->seguimientos->last()->oficina }},{{ $doc->seguimientos->last()->estado }}
                                </td>
                                <td>
                                    {{-- {!! Form::open(array('route'=>'doc.update','method'=>'PUT')) !!}
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <div class="form-group">
                                                <label for="oficina">Tipo de oficina</label>
                                                {!! Form::select('oficina[]',$oficinas,[],array('class'=>'form-control')) !!}
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <button type="submit" class="btn btn-primary">Enviar</button>
                                        </div>

                                    </div>
                                    {!! Form::close() !!} --}}
                                    {{-- {!! Form::open(array('route'=>'doc.update','method'=>'PUT')) !!} --}}




                                    <form action="{{ route('documents.destroy',$doc->id) }}" method="POST">
                                        {{-- <form action="{{ route('documents.update',$document->id) }}" method="POST">
                                            @csrf
                                            @method('PUT')

                                                <button type="submit" class="btn btn-primary">Enviar</button>
                                            </div>
                                        </form>                                         --}}
                                        <!-- Default dropright button -->
                                        {{-- <div class="btn-group dropright">
                                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Enviar
                                            </button>
                                            <div class="dropdown-menu">

                                                @foreach ($oficinas as $oficina)
                                                <form action="{{ route('doc.update',$oficina->id) }}" method="GET">
                                                    @csrf
                                                    @method('PUT')

                                                        <button type="submit" class="dropdown-item">{{ $oficina->name }}</button>

                                                </form>
                                                @endforeach
                                            </div>
                                        </div> --}}
                                        @can('editar-documento')
                                        <a class="btn btn-info" href="{{ route('documents.edit',$doc->id) }}">Editar</a>
                                        @endcan
                                        <a class="btn btn-outline-primary" href="{{ route('documents.show',$doc->id) }}">Ver</a>
                                        @csrf
                                        @method('DELETE')
                                        @can('borrar-documento')
                                        <button type="submit" class="btn btn-danger">Borrar</button>
                                        @endcan
                                    </form>

                                </td>
                                {{-- <td>
                                    @can('editar-documento')
                                    <a class="btn btn-primary" href="{{ route('documents.edit', $documento->id)  }}">Editar</a>
                                    @endcan
                                    @can('borrar-documento')
                                    {!! Form::open(['method'=>'DELETE','route'=>['documents.destroy',$documento->id],'style'=>'display:inline']) !!}
                                        {!! Form::submit('Borrar',['class'=>'btn btn-danger']) !!}
                                    {!! Form::close() !!}
                                    @endcan

                                </td> --}}
                            </tr>
                            @endforeach

                            </tbody>
                        </table>

                        <!-- Ubicamos la paginacion a la derecha -->
                        <div class="pagination justify-content-end">
                            {!! $documents->links() !!}
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection